### PR TITLE
add Debug implementation for enums

### PR DESCRIPTION
**Pull request by axos88**
Let's make these enums easier to print

### CODE REVIEW

**Comment by axos88** [comment]
I think if you merge #28 before this one you can avoid a conflict. Seems like a wtf in the git merge algorithm.

**Comment by Ogeon** [comment]
Sounds odd that they would conflict, but git has its odd sides. Either way, there's no hurry, so this can wait for the other one. :slightly_smiling_face:

**Comment by Ogeon** [comment]
Huh, conflicts anyway.

**Comment by Ogeon** [comment]
Great! Thanks!

**Pull request merged**
