### PR TITLE
Makefile no longer overwrites CC if it's set

### LINKED ISSUE #16: Don't force overwrite CC in makefile
Hello!

I am currently cross compiling a several libraries for rpi in my project, mostly by defining my own cross compiler in a build script. Unfortunately, rust-wiringpi force overwrites the CC I define as part of the build which causes rust-wiringpi to fail it's build. So, I would like to request CC only be set if it hasn't already been set before hand when building rust-wiringpi.

### PR DESCRIPTION
**Pull request by Lindenk**
Fixes #16

### CODE REVIEW

**Comment by Lindenk** [comment]
It looks like the failed test is seperate from what I've changed in the pull request.

**Comment by Ogeon** [comment]
Finally got a moment to look into this. The solutions seems simple and it looks like the tests are green on everything but 1.8.0, but that appears to be due to a dependency. I think it's fine to sneak in a small change in `.travis.yml` here, that just removes the 1.8.0 build. We can't support what our dependencies doesn't support.

**Comment by Ogeon** [comment]
Nice! Thank you!

**Comment by Ogeon** [comment]
@Lindenk I have finally gotten around to make a release, so you can switch back to using crates.io now.

**Comment by Lindenk** [comment]
Perfect! Thanks

**Pull request merged**
