### PR TITLE
Added std::ops::Not to Value enum

### LINKED ISSUE #30: Implement `!` (std::ops::Not) for `Value`
Because of the way rust handles Enums vs Integers, there is no convenient way to invert a logic level with rust-wiringpi. I propose `std::ops::Not` be implemented for `Value` so that it can be inverted:

`!High` would be `Low`
`!Low` would be `High`

### PR DESCRIPTION
**Pull request by Lindenk**
Fixes #30

### CODE REVIEW

**Comment by Lindenk** [comment]
Huh, it looks like the wiringpi dep is broken

**Comment by Ogeon** [comment]
Your code looks good. :+1: However, I don't know if this lib has much of a future anymore. I guess the broken dependency is due to [it being deprecated](http://wiringpi.com/wiringpi-deprecated/) (see also the message on https://git.drogon.net/). :frowning:

Well, thanks Gordon (in case you ever happen to drop by) for creating and maintaining it. It was very useful.

**Comment by Lindenk** [comment]
Thanks Gordon, you're project was incredibly helpful (And of course this wrapper too, thanks Ogeon). I suppose I'll port my stuff to sysfs_gpio moving forward

**Comment by Ogeon** [comment]
Sounds like the way to go. Learn from the good parts and improve elsewhere.

I'll close this, so it doesn't look like anything is still going on. Thanks for the contributions!

**Pull request closed without merging**
